- name: If OS is debian based
  import_tasks: debian.yaml
  when: ansible_facts['os_family']|lower == 'debian'
- name: If OS is redhat based
  import_tasks: redhat.yaml
  when: ansible_facts['os_family']|lower == 'redhat'
