# Install firewalld
- name: REDHAT Install firewalld
  yum:
    name: "firewalld"
    state: latest

# Open port 22 SSH
- name: REDHAT Open port 22 (SSH)
  firewalld:
    port: 22/tcp
    permanent: yes
    state: enabled
  notify:
    - reload-firewalld

# Enable firewalld
- name: REDHAT Enable firewalld
  service:
    name: "firewalld"
    enabled: yes

# Start firewalld
- name: REDHAT Start firewalld
  service:
    name: "firewalld"
    state: started
