- name: If OS is debian based
  import_tasks: debian-java.yaml
  when: ansible_facts['os_family']|lower == 'debian'
- name: If OS is redhat based
  import_tasks: redhat-java.yaml
  when: ansible_facts['os_family']|lower == 'redhat'
