# Install Filbeat Debian
- name: DEBIAN Install Filebeat
  apt:
    name: "filebeat"
    state: latest
  notify:
  - enable-filebeat-debian

# Copy Filebeat config to remote server
- name: DEBIAN Copy Filebeat Configuration
  copy: src=/etc/ansible/roles/filebeat/filebeat_config/filebeat.yml dest=/etc/filebeat/filebeat.yml

# Enable system logs in filebeat
- name: DEBIAN Enable Filebeat Module
  become: yes
  shell: filebeat modules enable system

# Enable apache logs in Filebeat
- name: DEBIAN Filebeat enable apache module
  become: yes
  shell: filebeat modules enable apache
  when: "'webservers' in group_names"

# Start Filebeat
- name: DEBIAN Start Filebeat
  service:
    name: "filebeat"
    state: started
