# Add GPG Key to APT
- name: DEBIAN Add Elasticsearch apt key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

# Add ELK Stack Repository to APT
- name: DEBIAN Add ELK Stack Repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    filename: elastic-7.x
    state: present
    update_cache: yes
