- name: If OS is debian based
  import_tasks: debian-elk-repo.yaml
  when: ansible_facts['os_family']|lower == 'debian'
- name: If OS is redhat based
  import_tasks: redhat-elk-repo.yaml
  when: ansible_facts['os_family']|lower == 'redhat'
